# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9a2897a181f02e11be7b9a4aa1cb8b5c4bed9900977a01da9526f60db5ae1491bb709aba1596711ef6bced62cf2fdeffe23313559ae6fabd11fda113ab43708

test:
  secret_key_base: 05a081502e14f1ea412111bafdce574760bd5c70b2480cfed0a4b2cd8de25e39b09f9af967861ed3dfb22310ad6c63fb0d445ef93c8a9bf80c749678b475ec8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
